import './globals.css'
import Link from 'next/link'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <div className="bg-white p-5">
        <Link href="/" className=" mr-2">Home</Link>
        <Link href="/list" className=" mr-2">List</Link>
        <Link href="/cart" className=" mr-2">Cart</Link>
        <Link href="/cart/payment" className=" mr-2">Pay</Link>
      </div>
        {children} 
      </body>
    </html>
  )
}
